import React from "react";
import Content from "./components/Content";

const ContentContainerOfDisclaimer = () => {
  // content of disclaimer
  const contentData = [
    {
      id: 1,
      heading: "Introduction & Consent",
      para1:
        "By using ThinkTweet, you agree to the terms outlined in this disclaimer.",
      para2:
        "ThinkTweet processes user-provided Twitter/X links using Large Language Models (LLMs) to generate structural and contextual analyses across five designated parameters.",
      para3: undefined,
    },
    {
      id: 2,
      heading: "Informational Purpose",
      para1:
        "All content generated by this platform is strictly for informational and educational purposes. The analysis provided should not be automatically treated as professional, academic, or legal advice.",
      para2: undefined,
      para3: undefined,
    },
    {
      id: 3,
      heading: "Accuracy of Information",
      para1:
        "While our core goal is to provide precise and objective structural analysis, we cannot guarantee that the generated output is entirely complete, current, or error-free.",
      para2: undefined,
      para3: undefined,
    },
    {
      id: 4,
      heading: "AI-Generated Content & Inherent Bias",
      para1:
        "All analysis results are generated or assisted by artificial intelligence. LLMs are fallible; they can make mistakes, misunderstand nuance, or produce inaccurate conclusions.",
      para2:
        "Furthermore, LLMs can sometimes reflect or enforce societal and misogynistic biases present in their training data. Feminism and feminist discourse are core values of this project.",
      para3:
        "We acknowledge these AI limitations and are actively working to improve the model's alignment. If you encounter skewed or biased results, we encourage you to inform us so we can continue to refine the system.",
    },
    {
      id: 5,
      heading: "No Guarantee of Results",
      para1:
        "We provide no warranties regarding the output. The analysis, recommendations, parameter scores, and statistics provided by ThinkTweet may not always be accurate, applicable, or useful for your specific context.",
      para2: undefined,
      para3: undefined,
    },
    {
      id: 6,
      heading: "User Decisions and Reliance",
      para1:
        "Users must independently verify any important information before making decisions based on this website's output. Please do not trust our analysis blindly.",
      para2:
        "We encourage you to use ThinkTweet to enhance your understanding of digital discourse, but you must draw your own final conclusions.",
      para3: undefined,
    },
    {
      id: 7,
      heading: "Third-Party Content & External Links",
      para1:
        "ThinkTweet relies on external APIs and third-party systems. We are not responsible for the accuracy, availability, or uptime of these third-party integrations.",
      para2:
        "Additionally, you may find external links to the developer's LinkedIn or GitHub; we do not control these external domains and are not responsible for their content or privacy policies.",
      para3: undefined,
    },
    {
      id: 8,
      heading: "Privacy & Data Security",
      para1:
        "We utilize industry-standard security measures to protect your data. However, as with any digital platform, no system is 100% bulletproof. Because this is fundamentally an educational project, your peace of mind is our priority.",
      para2:
        "If you feel hesitant about data privacy, you are entirely welcome to use a temporary, random, or anonymous email address to log in. We do not block disposable email IDs.",
      para3: undefined,
    },
    {
      id: 9,
      heading: "Open Source & Community Driven",
      para1:
        "ThinkTweet believes in structural transparency. Our source code is publicly available on GitHub. You are welcome to visit the repository to inspect the mechanics of the platform, and community contributions are highly encouraged.",
      para2: undefined,
      para3: undefined,
    },
    {
      id: 10,
      heading: "Availability & Technical Issues",
      para1:
        "Our service is provided on an 'as-is' and 'as-available' basis. The platform may occasionally be unavailable, interrupted, or experience technical errors without prior notice.",
      para2: undefined,
      para3: undefined,
    },
    {
      id: 11,
      heading: "Limitation of Liability",
      para1:
        "To the fullest extent permitted by applicable law, ThinkTweet, its developers, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of your access to, reliance on, or use of the website and its AI-generated outputs.",
      para2: undefined,
      para3: undefined,
    },
    {
      id: 12,
      heading: "Changes to this Disclaimer",
      para1:
        "We reserve the right to update or modify this disclaimer at any time as the platform, its underlying LLMs, or its services evolve.",
      para2: undefined,
      para3: undefined,
    },
    {
      id: 13,
      heading: "Contact Information",
      para1:
        "If you have any further questions or wish to report anomalous AI behavior, please contact us at:",
      para2: undefined,
      para3: undefined,
    },
  ];
  return (
    <div>
      {contentData.map((elem) => {
        return (
          <Content
            key={elem.id}
            contentNum={elem.id}
            contentHeading={elem.heading}
            contentParaOne={elem.para1}
            contentParaTwo={elem.para2}
            contentParaThree={elem.para3}
          />
        );
      })}
    </div>
  );
};

export default ContentContainerOfDisclaimer;
