import React from "react";

const CardOfPrivacy = ({ num, heading, para, listArray }) => {

  //important notes
  //key prop of the sub items are 1a, 1b, 1c and 1d respectively
  //and it's automatically generated by combination num + character
  return (
    <div>
      <h2 className="text-xl">{`${num}. ${heading}`}</h2>
      <p>{para}</p>
      <ul>
        {listArray.map((elem) => {
          return (
            <li
              key={num + String.fromCharCode(97 + listArray.indexOf(elem))}
            >
              <span className="font-bold">{elem.head} </span>
              {elem.content}
            </li>
          );
        })}
      </ul>
    </div>
  );
};

export default CardOfPrivacy;
