import React from "react";
import {twMerge} from "tailwind-merge"

const CardOfPrivacy = ({ num, heading, para, listArray }) => {

  //important notes
  //key prop of the sub items are 1a, 1b, 1c and 1d respectively
  //and it's automatically generated by combination num + character
  return (
    <div>
      <h2 className={twMerge("text-xl text-brand-primary font-bold mt-10 mb-5", num === 1 && "mt-0")}>{`${num}. ${heading}`}</h2>
      <p className="mb-5 text-brand-secondary">{para}</p>
      <ul>
        {listArray.map((elem) => {
          return (
            <li
              key={num + String.fromCharCode(97 + listArray.indexOf(elem))}
              className="list-disc ml-6 mb-3 text-brand-secondary max-phone:ml-3.5 max-phone:mb-5"
            >
              <span className="font-bold text-brand-primary">{elem.head} </span>
              {elem.content}
            </li>
          );
        })}
      </ul>
    </div>
  );
};

export default CardOfPrivacy;
